all_files = [
    "Accounting and Financial Services.docx",
    "Automobile engineering.docx",
    "Careeer Option in Human Resource Management.docx",
    "Careeer Option in Human Rights.docx",
    "Career in acturial science.docx",
    "Career option in Agricultural Biochemistry.docx",
    "Career Option in Agricultural Engineering.docx",
    "Career Option in Animation.docx",
    "Career Option in Anthropology.docx",
    "Career option in Architectural Service.docx",
    "Career Option in Automation.docx",
    "Career Option in Aviation.docx",
    "Career Option in Ayurveda.docx",
    "Career option in Banking.docx",
    "Career Option in Beauty Care.docx",
    "Career Option in Biology.docx",
    "Career Option in Book Publishing.docx",
    "Career Option in BPO.docx",
    "Career Option in Catering.docx",
    "Career Option in Ceramics.docx",
    "Career Option in Chemical Engineering.docx",
    "Career Option in Civil Engineering.docx",
    "Career Option in Civil Services.docx",
    "Career Option in Company Secretary.docx",
    "Career Option in Construction Engineering.docx",
    "Career Option in Dairy Technology.docx",
    "Career Option in Dance.docx",
    "Career Option in Data Processing.docx",
    "Career Option in Dental.docx",
    "Career Option in Drama.docx",
    "Career Option in Drug Regulatory Affair.docx",
    "Career Option in Electrical.docx",
    "Career Option in Electronics.docx",
    "Career Option in Energy Professionals.docx",
    "Career option in Event Management.docx",
    "Career Option in Fabrication Technology.docx",
    "Career Option in Fashion Techonology.docx",
    "Career Option in Fibre Technology.docx",
    "Career Option in Fine Arts.docx",
    "Career Option in Fishery Science.docx",
    "Career Option in Floriculture.docx",
    "Career Option in Food Processing Technolog1.docx",
    "Career Option in Food Processing Technology.docx",
    "Career Option in Footwear.docx",
    "Career Option in Forensic Medicine.docx",
    "Career Option in Foundry and Forging.docx",
    "Career Option in Front Office Reception.docx",
    "Career Option in Gemology.docx",
    "Career Option in Genetic Engineering.docx",
    "Career Option in Hardware.docx",
    "Career Option in Home Science.docx",
    "Career Option in Homeopathic.docx",
    "Career Option in Hospital Health Systems Management.docx",
    "Career Option in Hotel Management.docx",
    "Career Option in Housekeeping.docx",
    "Career Option in Indian Army.docx",
    "Career Option in Indian Navy.docx",
    "Career Option in Industrial Engineering.docx",
    "Career Option in Information Science.docx",
    "Career Option in Information Technology.docx",
    "Career Option in Institutional Sales.docx",
    "Career Option in Instrumentation Engineering.docx",
    "Career Option in International Business.docx",
    "Career Option in Journalism.docx",
    "Career Option in Lab Chemistry.docx",
    "Career Option in Language Specialist.docx",
    "Career Option in Logistics Supply Chain.docx",
    "Career Option in Marine Engineering.docx",
    "Career Option in Marketing.docx",
    "Career Option in Mechanical Engineering.docx",
    "Career Option in Media.docx",
    "Career Option in Medical Laboratory Technology.docx",
    "Career Option in Medicine.docx",
    "Career Option in Mining.docx",
    "Career Option in Music.docx",
    "Career Option in Nursing.docx",
    "Career Option in Nutrition And Dietetics.docx",
    "Career Option in Optometry.docx",
    "Career Option in Packaging.docx",
    "Career Option in Painting.docx",
    "Career Option in Pharmacy.docx",
    "Career Option in Photography.docx",
    "Career Option in Physiotherapy.docx",
    "Career Option in Plastic.docx",
    "Career Option in Political Science.docx",
    "Career Option in Polymer.docx",
    "Career Option in Printing Technology.docx",
    "Career Option in Production Engineering.docx",
    "Career Option in Psychology.docx",
    "Career Option in Purchasing Material Management.docx",
    "Career Option in Quality Assurance and Quality Control.docx",
    "Career Option in Radiology.docx",
    "Career Option in Religion.docx",
    "Career Option in Retail Sales.docx",
    "Career Option in Rubber Technology.docx",
    "Career Option in Sales Support.docx",
    "Career Option in Sculpture.docx",
    "Career Option in Securities.docx",
    "Career Option in Siddha.docx",
    "Career Option in Special Education.docx",
    "Career Option in Speech and Language Pathology.docx",
    "Career Option in Sports.docx",
    "Career Option in Statistics.docx",
    "Career Option in Sugar Mills.docx",
    "Career Option in Tax.docx",
    "Career Option in Teacher Training And Education.docx",
    "Career Option in Telecommunications.docx",
    "Career Option in Textile Technology.docx",
    "Career Option in Trade.docx",
    "Career Option in Translation.docx",
    "Career Option in Travel And Tourism.docx",
    "Career Option in Unani Medicine.docx",
    "Career Option in Veterinary Science.docx",
    "Career Option in Yoga.docx",
    "Careers Option in Advertising.docx",
    "Carrer Option in Astronomy.docx",
    "chartered account.docx",
    "Cost and Works Accountants.docx",
]
